using System;
using Elastic.Apm.DiagnosticSource;

namespace Elastic.Apm.AspNetCore.DiagnosticListener
{
	/// <summary>
	/// Manages all listeners that are generated by Types which are part of .netstandard 2.0
	/// </summary>
	public class AspNetCoreDiagnosticsSubscriber : IDiagnosticsSubscriber
	{
		/// <summary>
		/// Start listening for diagnosticsource events. Only listens for sources that are part of the Agent.Core package.
		/// </summary>
		public IDisposable Subscribe(IApmAgent agent) => System.Diagnostics.DiagnosticListener
			.AllListeners
			.Subscribe(new DiagnosticInitializer(new [] { new AspNetCoreDiagnosticListener(agent),  }));
	}
}
