---
name: Documentation Only Change Set
description: Checks if the proposed changes are only documentation changes

outputs:
  docs-changes-only:
    description: "True if only documentation file changed"
    value: ${{ steps.changed-files.outputs.docs_any_changed == 'true' && steps.changed-files.outputs.not_docs_any_changed == 'false' }}
  ci-changes-only:
    description: "True if only ci files changed"
    value: ${{ steps.changed-files.outputs.ci_any_changed == 'true' && steps.changed-files.outputs.not_ci_any_changed == 'false' }}
    
runs:
  using: "composite"
  steps:
    - uses: tj-actions/changed-files@03334d095e2739fa9ac4034ec16f66d5d01e9eba # v44.5.1
      name: 'Gets the current changeset'
      id: changed-files
      with:
        files_yaml: |
          doc:
            - '*.md'
            - '*.asciidoc'
            - 'docs/**'
          not_docs:
            - '!*.md'
            - '!*.asciidoc'
            - '!docs/**'
          
          ci:
            - '.github/**'
          not_ci:
            - '!.github/**'
