version: 2
updates:

  # GitHub actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/workflows/*"
    reviewers:
      - "elastic/observablt-ci"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      github-actions:
        patterns:
          - "*"
