ifdef::env-github[]
NOTE: Release notes are best read in our documentation at
https://www.elastic.co/guide/en/apm/agent/dotnet/current/release-notes.html[elastic.co]
endif::[]

:issue: https://github.com/elastic/apm-agent-dotnet/issues/

////
[[release-notes-x.x.x]]
==== x.x.x - YYYY/MM/DD

[float]
===== Breaking changes

[float]
===== Features
- Cool new feature: {pull}2526[#2526]

[float]
===== Bug fixes
////

[[release-notes-1.x]]
=== .NET Agent version 1.x


[[release-notes-1.11.0]]
==== 1.11.0

[float]
===== Features
- {pull}1302[#1302] Prefer W3C traceparent over elastic-apm-traceparent
- {pull}1310[#1310] Add TraceContextIgnoreSampledFalse config setting
- {pull}1342[#1342] CosmosDb support (issue: {issue}1154[#1154])
- {pull}1271[#1271] Support "Time spent by span type" (aka Breakdown metrics) (issue: {issue}227[#227])
- {pull}1331[#1331] Create transactions for Azure Service Bus Processors (issue: {issue}1321[#1321])

[[release-notes-1.10.0]]
==== 1.10.0

[float]
===== Features
- {pull}1225[#1225] Add instrumentation for Azure Service Bus (issue: {issue}1157[#1157])
- {pull}1247[#1247] Add Azure storage integration (issues: {issue}1156[#1156] and {issue}1155[#1155])
- {pull}1241[#1241] Internalize `Newtonsoft.Json` - no more dependency on `Newtonsoft.Json`
- {pull}1275[#1275] Internalize `Ben.Demystifier` - no more dependency on `Ben.Demystifier` (issue: {issue}1232[#1232])
- {pull}1215[#1215] Add MongoDb support (issue: {issue}1158[#1158])
- {pull}1277[#1277] Capture inner exceptions (issue: {issue}1267[#1267])
- {pull}1290[#1290] Add configured hostname (issue: {issue}1289[#1289])
- {pull}1288[#1288] Use TraceLogger as default logger in ASP.NET Full Framework (issue: {issue}1263[#1263])

[float]
===== Bug fixes
- {pull}1252[#1252] Fix issue around setting `Recording` to `false` (issue: {issue}1250[#1250])
- {pull}1259[#1259] ASP.NET: Move error capturing to Error event handler
- {pull}1305[#1305] Use Logger to log exception in AgentComponents initialization (issue: {issue}1254[#1254])
- {pull}1311[#1311] Fix `NullReferenceException` in Elastic.Apm.Extensions.Logging(issue: {issue}1309[#1309])

[float]
===== Breaking changes
- {pull}1306[#1306] Do not capture HTTP child spans for Elasticsearch (issue: {issue}1276[#1276])

[[release-notes-1.9.0]]
==== 1.9.0

[float]
===== Features
- {pull}925[#925] Add GC time (issue: {issue}922[#922])
- {pull}1147[#1147] Propagate sample rate through `tracestate` (issue: {issue}1021[#1021])

[float]
===== Bug fixes
- {pull}1189[#1189] Get transaction name from Web API controller route template

[float]
===== Breaking changes
- {pull}1161[#1161] and {pull}1162[#1162] The agent tries to never throw any exception. Specifically instead of throwing `InstanceAlreadyCreatedException`, it will print an error log.

[[release-notes-1.8.1]]
==== 1.8.1

[float]
===== Features
- {pull}1196[#1196] Add GC Heap Stats capturing for .NET 5.0 (issue: {issue}1195[#1195])

[float]
===== Bug fixes
- {pull}1192[#1192] Lazily access the agent in ElasticApmProfiler redis integration (issue: {issue}1190[#1190])
- {pull}1198[#1198] Add TargetFramework NET5.0 to Elastic.Apm.AspNetCore and related packages (issue: {issue}1194[#1194])

[[release-notes-1.8.0]]
==== 1.8.0

[float]
===== Features
- {pull}1063[#1063] Add support for capturing redis commands from StackExchange.Redis
(<<setup-stackexchange-redis,documentation>>) (issue: {issue}874[#874])
- {pull}1065[#1065] Introduce `ServerUrl` config - (`ServerUrls` is still working but will be removed in the future) (issue: {issue}1035[#1035])
- {pull}1048[#1048] Support for more k8s cgroup path patterns (issue: {issue}968[#968])
- {pull}1082[#1082] `SanitizeFieldNames` config became changeable though Kibana central configuration
- {pull}1083[#1083] Azure App Service cloud metadata collection
- {pull}1135[#1135] Capture error logs as APM errors from `Microsoft.Extensions.Logging` automatically and extend the Public API to capture custom logs as APM errors (issue: {issue}894[#894])
- {pull}1096[#1096] Support changing log level through Kibana central configuration and support `"off"` level (issue: {issue}970[#970])

[float]
===== Bug fixes
- {pull}1081[#1081] `NullReferenceException` with disabled agent on `Transaction.Custom` (issue: {issue}1080[#1080])
- {pull}1078[#1078] ASP.NET Core, enabled=false in `appsettings.json` does not disable public Agent API (issue: {issue}1077[#1077])
- {pull}1115[#1115] `System.IO.IOException` on ASP.NET Classic (issue: {issue}1113[#1113])
- {pull}1118[#1118] Memory issue with gRPC  (issue: {issue}1116[#1116])
- {pull}1124[#1124] Ensuring ETW sessions are terminated on agent shutdown (issue: {issue}897[#897])
- {pull}1109[#1109] `NullReferenceException` with custom `IConfigurationReader` implementation in `MetricsCollector`
- {pull}1138[#1138] and {pull}1165[#1165] Fixes around zero code change agent setup with `DOTNET_STARTUP_HOOKS`
- {pull}1115[#1115] Access `Request.InputStream` only when SOAP header present (issue: {issue}1113[#1113])

[[release-notes-1.7.1]]
==== 1.7.1

[float]
===== Features
- {pull}1057[#1057] Introduce `GetLabel<T>` method on `IExecutionSegment` (issue: {issue}1033[#1033])

[float]
===== Bug fixes
- {pull}1052[#1052] Increased transaction duration due to stack trace capturing (issue: {issue}1039[#1039])
- {pull}1053[#1053] Warning with `Synchronous operations are disallowed` on ASP.NET Core during request body capturing (issue: {issue}1044[#1044])
- {pull}1042[#1042] SqlClient instrumentation on .NET 5 (issue: {issue}1025[#1025])
- {pull}1060[#1060] `UseAllElasticApm` with `IHostBuilder` missing auto instrumentation (issue: {issue}1059[#1059])

[[release-notes-1.7.0]]
==== 1.7.0

[float]
===== Features
- {pull}828[#828] Agent loading with zero code change on .NET Core (issue: {issue}71[#71])
- {pull}969[#969] gRPC support (issue: {issue}478[#478])
- {pull}974[#974] Add ability to configure Hostname (issue: {issue}932[#932])
- {pull}997[#997] Add Enabled and Recording configuration (issue: #122)
- {pull}912[#912] Add `FullFrameworkConfigurationReaderType` config to load custom configuration reader on ASP.NET
- {pull}978[#978] Capture User id and email on ASP.NET (issue: #540)
- {pull}982[#982] Support boolean and numeric labels in addition to string labels  (issues: {issue}967[#967], {issue}788[#788], {issue}473[#473], {issue}192[#191], {issue}788[#788], {issue}473[#473], {issue}191[#191])
- {pull}1000[#1000] Collecting metrics based on cGroup (issue: {issue}937[#937])
- {pull}1002[#1002] `ITransaction.SetService` API to support multiple services in a single process (issue: {issue}1001[#1001])
- {pull}1003[#1003] Collecting cloud metadata (supporting AWS, Azure,  GCP) (issue: {issue}918[#918])
- {pull}973[#973] Transaction grouping on ASP.NET (issue: {issue}[#201])
- {pull}913[#913] Entity Framework 6 support on .NET Core (issue: {issue}902[#902])


[float]
===== Bug fixes
- {pull}992[#992] On ASP.NET Core `CurrentTransaction` is null in some cases (issues: {issue}934[#934], {issue}972[#972])
- {pull}971[#971] Avoid double initialization in `HostBuilderExtensions`
- {pull}999[#999] Capture body with large file error (issue: {issue}960[#960])

[float]
===== Breaking changes
- Binary compatibility on `IExecutionSegment.CaptureException` and `IExecutionSegment.CaptureError` with libraries depending on previous version. If this happens you need to update `Elastic.Apm` to 1.7.0 in your projects (Issue: ({issue}1067)[#1067])

[[release-notes-1.6.1]]
==== 1.6.1

[float]
===== Bug fixes
- Service map: missing connection between .NET services ({pull}909[#909])

[[release-notes-1.6.0]]
==== 1.6.0

[float]
===== Features
- Elasticsearch client instrumentation {pull}329[#329]
- Introducing `Elastic.Apm.Extensions.Hosting` package with an extension method on `IHostBuilder` {pull}537[#537]
- Stack trace improvements: async call stack demystification ({pull}847[#847]) and showing frames from user code for outgoing HTTP calls ({pull}845[#845])
- Making fields on `IError` public {pull}847[#847]
- Service map improvements: {pull}893[#893]

[float]
===== Bug fixes
- Missing traces from the Kibana traces list due to setting `Transaction.ParentId` to an `Activity` {pull}888[#888]
- Exception around runtime detection {pull}859[#859]
- Missing outgoing HTTP calls in .NET Framework applications and causing memory issues {pull}896[#896]

[[release-notes-1.5.1]]
==== 1.5.1

[float]
===== Bug fixes
- Memory issue in SqlEventListener {pull}851[#851]

[[release-notes-1.5.0]]
==== 1.5.0

[float]
===== Features
- Auto instrumentation for `SqlClient` (<<setup-sqlclient,documentation>>)
- Introducing Filter API {pull}792[#792] (<<filter-api,documentation>>)
- Auto-detect culprit for exceptions {pull}740[#740]
- New config settings: `ExcludedNamespaces`, `ApplicationNamespaces` (<<config-all-options-summary,documentation>>)
- Keep `Activity.Current.TraceId` in sync with the Trace ID used by the agent {pull}800[#800]
- Report Kubernetes system metadata {pull}741[#741]

[float]
===== Bug fixes
- Database connection string parsing issue with Oracle {pull}795[#795]

[[release-notes-1.4.0]]
==== 1.4.0

[float]
===== Features
- Introducing `ITransaction.EnsureParentId()` to integrate with RUM in dynamically loaded HTML pages (including page loads in ASP.NET Core) {pull}771[#771]
- New config setting: `ApiKey` {pull}733[#733]

[float]
===== Bug fixes
- Memory issue in .NET Full Framework with default metrics turned on {pull}750[#750]
- Parsing for Oracle connection strings {pull}749[#749]
- `StackOverflowException` when using the `Elastic.Apm.SerilogEnricher` package and the log level is set to `Verbose` {pull}753[#753]

[float]
===== Breaking changes
- We have some changes that are technically breaking changes. We made some helper classes internal that were never meant to be public. These are: `Elastic.Apm.Helpers.AgentTimeInstant`,  `Elastic.Apm.Helpers.ContractExtensions`,  `Elastic.Apm.Helpers.ObjectExtensions`, `Elastic.Apm.Helpers.ToStringBuilder`. None of these classes were documented or mentioned as part of the Public Agent API. We expect no usage of these classes outside the agent.

[[release-notes-1.3.1]]
==== 1.3.1

[float]
===== Bug fixes
- Fix log spamming issues  {pull}736[#736], {pull}738[#738]
- Fix turning HTTP 415 responses in ASP.NET Core to HTTP 500 when request body capturing is active {pull}739[#739]
- Fix disabling GC metrics collection in case no GC is triggered during the first "5*MetricsInterval" of the process {pull}745[#745]

[[release-notes-1.3.0]]
==== 1.3.0

[float]
===== Features
- New GC metrics: `clr.gc.count`, `clr.gc.gen[X]size`, where [X]: heap generation {pull}697[#697]
- Capturing SOAP action name as part of the transaction name {pull}683[#683]
- New config options: `ServiceNodeName`, `VerifyServerCert`, `DisableMetrics`, `UseElasticTraceparentHeader` (<<config-all-options-summary,docs>>)
- Full https://www.w3.org/TR/trace-context[W3C TraceContext] support {pull}717[#717]


[float]
===== Bug fixes
- Fix transaction name generation in ASP.NET Core 3.x {pull}647[#647]
- Fix around HTTP request body sanitization {pull}712[#712]


[[release-notes-1.2.0]]
==== 1.2.0

[float]
===== Features

- Entity framework support with Interceptor (<<setup-ef6,docs>>)
- Sanitization of HTTP headers and request body (<<config-sanitize-field-names,docs>>)
- Central configuration - 2 new configs: `CAPTURE_BODY` and `TRANSACTION_MAX_SPANS`. {pull}577[#577].
- Support for global labels (<<config-global-labels,docs>>)
- Custom context (<<api-transaction-context,docs>>)
- Dropping support for ASP.NET Core 2.0 (which is already end of life) (<<supported-web-frameworks,docs>>)

[float]
===== Bug fixes

- De-dotting labels. {pull}583[#583].
- Request body capturing TypeLoadException in ASP.NET Core 3.0. {pull}604[#604].
- Metrics collection: filtering NaN and Infinity. {pull}589[#589].

[[release-notes-1.1.2]]
==== 1.1.2

[float]
===== Bug fixes

- Capturing request body with ASP.NET Core erased the body in some scenarios {pull}539[#539].
- Integration with Serilog caused missing logs and diagnostic traces with `NullReferenceException` {pull}544[#544], {pull}545[#545].

[[release-notes-1.1.1]]
==== 1.1.1

[float]
===== Features

Configure transaction max spans. {pull}472[#472]

[float]
===== Bug fixes

Fixing missing "Date Modified" field on the files from the `1.1.0` packages causing an error while executing `dotnet pack` or `nuget pack` on a project with Elastic APM Agent packages. {pull}527[#527]

[[release-notes-1.1.0]]
==== 1.1.0

[float]
===== Features

- ASP.NET Support, documentation can be found <<setup-asp-dot-net,here>>
- Central configuration (Beta)

[float]
===== Bug fixes

- Addressed some performance issues {pull}359[#359]
- Improved error handling in ASP.NET Core {pull}512[#512]
- Fix for mono {pull}164[#164]

[[release-notes-1.0.1]]
==== 1.0.1

[float]
===== Bug fixes

- `NullReferenceException` on .NET Framework with outgoing HTTP calls created with `HttpClient` in case the response code is HTTP3xx {pull}450[#450]
- Added missing `net461` target to the https://www.nuget.org/packages/Elastic.Apm/[`Elastic.Apm`] package
- Handling <<api-transaction-tags,`Labels`>> with `null` {pull}429[#429]

[float]
===== Features

- Reading request body in ASP.NET Core. Also introduced two new settings: `CaptureBody` and `CaptureBodyContentTypes`. By default this feature is turned off, this is an opt-in feature and can be turned on with the `CaptureBody` setting. {pull}402[#402]


[[release-notes-1.0.0]]
==== 1.0.0 GA

The 1. GA release of the Elastic APM .NET Agent. Stabilization of the 1.0.0-beta feature for production usage.

[float]
===== Features

- Out of the box integration with `ILoggerFactory` and the logging  infrastructure in ASP.NET Core {pull}249[#249]
- Introduced `StackTraceLimit` and `SpanFramesMinDurationInMilliseconds` configs {pull}374[#374]
- The Public Agent API now support `Elastic.Apm.Agent.Tracer.CurrentSpan` {pull}391[#391]

[float]
===== Bug fixes

- Thread safety for some bookkeeping around spans {pull}394[#394]
- Auto instrumentation automatically creates sub-spans in case a span is already active {pull}391[#391]


[float]
===== Breaking changes

We have some breaking changes in this release. We wanted to do these changes prior to our GA release and with this we hopefully avoid breaking changes in the upcoming versions.

- For better naming we replaced the `Elastic.Apm.All` packages with `Elastic.Apm.NetCoreAll`  {pull}371[#371]
- Based on feedback we also renamed the `UseElasticApm()` method in the `Elastic.Apm.NetCoreAll` package to `UseAllElasticApm` - this method turns on every component of the Agent for ASP.NET Core. {pull}371[#371]
- Our logger abstraction, specifically the `IApmLogger` interface changed: {pull}389[#389]
- To follow the https://www.elastic.co/guide/en/ecs/current/index.html[Elastic Common Schema (ECS)], we renamed our `Tags` properties to `Labels`. {pull}416[#416]

[[release-notes-beta]]
=== .NET Agent version beta/preview

[[release-notes-beta1]]
==== Beta1 release

[float]
===== Features

- Distributed tracing support (based on W3C Trace Context)
- Sampling
- Metrics (Process and System CPU usage, Free and total Memory, Process working set and private bytes)
- Capture Docker container id (linux containers only)

[float]
===== Improvements

- ASP.NET Core: better transaction names based on routing, capture authenticated users
- Public Agent API: create sub spans, serialize and deserialize traceparent
- Stack traces contain fully qualified class names and real method names in case of  async methods

[[release-notes-preview2]]
==== Preview release 2

[float]
===== Features

- <<config-secret-token,`SecretToken` setting>> - with this you can use the agent with Elastic Cloud.
- Intake V2 protocol to server communication - support for APM Server 7.x
- Extended public agent API: support for setting custom HTTP and Database related fields.
- Improved logging.

Packages can be found on https://www.nuget.org/packages?q=Elastic.apm[nuget.org].

[[release-notes-preview1]]
==== Preview release 1

[float]
===== Features

- ASP.NET Core auto instrumentation
- Entity Framework Core auto instrumentation
- https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netstandard-2.0[HttpClient] auto instrumentation

- <<public-api,Public Agent API>>

We shipped the following packages:

- Elastic.Apm.All: This is a meta package that references every other Elastic APM .NET agent package. If you plan to monitor a typical ASP.NET Core application that depends on the https://www.nuget.org/packages/Microsoft.AspNetCore.All[Microsoft.AspNetCore.All] package and uses Entity Framework Core then you should reference this package.
In order to avoid adding unnecessary dependencies in applications that aren’t depending on the https://www.nuget.org/packages/Microsoft.AspNetCore.All[Microsoft.AspNetCore.All] package we also shipped some other packages - those are all referenced by the Elastic.Apm.All package.

- Elastic.Apm: This is the core of the agent, which we didn’t name “Core”, because someone already took that name :) This package also contains the Public Agent API and it is a .NET Standard 2.0 package. We also ship every tracing component that traces things that are part of .NET Standard 2.0 in this package, which includes the monitoring part for HttpClient.
Elastic.Apm.AspNetCore: This package contains ASP.NET Core monitoring related code. The main difference between this package and the Elastic.Apm.All package is that this package does not reference the

- Elastic.Apm.EntityFrameworkCore package, so if you have an ASP.NET Core application that does not use EF Core and you want to avoid adding additional unused references, you should use this package.

- Elastic.Apm.EntityFrameworkCore: This package contains EF Core monitoring related code.
