policies:
  - name: Handle apm-data server specs
    policy: ghcr.io/elastic/oblt-updatecli-policies/apm/apm-data-spec:0.6.0@sha256:c0bbdec23541bed38df1342c95aeb601530a113db1ff11715c1c7616ed5e9e8b
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/apm-data-spec.yml

  - name: Handle apm gherkin specs
    policy: ghcr.io/elastic/oblt-updatecli-policies/apm/apm-gherkin:0.6.0@sha256:dbaf4d855c5c212c3b5a8d2cc98c243a2b769ac347198ae8814393a1a0576587
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/apm-gherkin.yml

  - name: Handle apm json specs
    policy: ghcr.io/elastic/oblt-updatecli-policies/apm/apm-json-specs:0.2.0@sha256:969a6d21eabd6ebea66cb29b35294a273d6dbc0f7da78589c416aedf08728e78
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/apm-json-specs.yml
