using System;

namespace Elastic.Apm.Helpers
{
	public static class RandomGenerator
	{
		private static readonly Random Global = new Random();

		[ThreadStatic]
		private static Random _local;

		private static Random GetInstance()
		{
			var inst = _local;
			if (inst == null)
			{
				int seed;
				lock (Global) seed = Global.Next();
				_local = inst = new Random(seed);
			}
			return inst;
		}

		public static void GenerateRandomBytes(byte[] bytes) => GetInstance().NextBytes(bytes);

		/// <summary>
		/// Creates a random generated byte array hex encoded into a string.
		/// </summary>
		/// <param name="bytes">The byte array that will be filled with a random number - this defines the length of the generated random bits</param>
		/// <returns>The random number hex encoded as string</returns>
		public static string GenerateRandomBytesAsString(byte[] bytes)
		{
			GenerateRandomBytes(bytes);
			return BitConverter.ToString(bytes).Replace("-", "").ToLower();
		}

		public static Double GenerateRandomDoubleBetween0And1() => GetInstance().NextDouble();
	}
}
