:nuget: https://www.nuget.org/packages
:dot: .

[[setup]]
== Set up the Agent

The .NET agent can be added to an application in three different ways

Profiler runtime instrumentation::
The agent supports auto instrumentation without any code change and without
any recompilation of your projects. See <<setup-auto-instrumentation>>.

NuGet packages::
The agent ships as a set of <<packages, NuGet packages>> available on https://nuget.org[nuget.org].
You can add the Agent and specific instrumentations to a .NET application by 
referencing one or more of these packages and following the package documentation.

Host startup hook::
On **.NET Core 3.0+ or .NET 5+**, the agent supports auto instrumentation without any code change and without
any recompilation of your projects. See <<zero-code-change-setup, Zero code change setup on .NET Core>>
for more details.

[float]
== Get started

* <<setup-auto-instrumentation>>
* <<setup-asp-net-core>>
* <<setup-dotnet-net-core>>
* <<setup-asp-dot-net>>
* <<setup-azure-functions>>
* <<setup-general, Manual instrumentation>>

include::./setup-auto-instrumentation.asciidoc[]
include::./setup-asp-net-core.asciidoc[]
include::./setup-dotnet-net-core.asciidoc[]
include::./setup-asp-dot-net.asciidoc[]
include::./setup-azure-functions.asciidoc[]

[[setup-general]]
=== Other .NET applications

If you have a .NET application that is not covered in this section, you can still use the agent and instrument your application manually.

To do this, add the {nuget}/Elastic.Apm[Elastic.Apm] package to your application and use the <<public-api>> to manually create spans and transactions.
