// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SampleAspNetCoreApp.Data;

namespace SampleAspNetCoreApp.Migrations
{
	[DbContext(typeof(SampleDataContext))]
	internal partial class SampleDataContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

			modelBuilder.Entity("SampleAspNetCoreApp.Data.User", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd();

				b.Property<string>("Name");

				b.HasKey("Id");

				b.ToTable("Users");
			});
#pragma warning restore 612, 618
		}
	}
}
