name: Linux
on:
  pull_request:

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build - linux
        run: |-
          DOTNET_ROOT=${GITHUB_WORKSPACE}/.dotnet
          PATH=${GITHUB_WORKSPACE}/.dotnet/tools:${GITHUB_WORKSPACE}/.dotnet
          mkdir -p ${DOTNET_ROOT}
          # Download .Net SDK installer script
          curl -s -O -L https://dot.net/v1/dotnet-install.sh
          chmod ugo+rx dotnet-install.sh
          # Install .Net SDKs
          ./dotnet-install.sh --install-dir "${DOTNET_ROOT}" -version '3.1.100'
          ./dotnet-install.sh --install-dir "${DOTNET_ROOT}" -version '5.0.100'
          ./dotnet-install.sh --install-dir "${DOTNET_ROOT}" -version '6.0.100'
          .ci/linux/build.sh
          .ci/linux/release.sh true
          rustup default 1.57.0
          cargo install --force cargo-make
          ./build.sh profiler-zip
