name: Linux Test
on:
  pull_request:

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env variables
        run: |-
          echo "${GITHUB_WORKSPACE}/.dotnet/tools" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/.dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=${GITHUB_WORKSPACE}/.dotnet" >> $GITHUB_ENV
      - name: Prepare tools
        run: .ci/linux/prepare-dotnet-tools.sh
      - name: Test - linux
        run: |-
          .ci/linux/test.sh