---
# Publish a snapshot. A "snapshot" is a packaging of the latest *unreleased* APM agent,
# published to a known GCS bucket for use in edge demo/test environments.
name: snapshoty

on:
  workflow_run:
    workflows: ['test-linux']
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    # used by opbeans .NET to reference the on commit nuget packages
    # TODO: update opbeans to use our feedz.io packages
    - uses: actions/download-artifact@v3
      with:
        name: snapshoty-linux
        path: build/output

    # - uses: actions/download-artifact@v3
    #   with:
    #     name: snapshoty-windows
    #     path: build/output

    - name: Display structure of downloaded files
      run: find build -type f

    - name: Publish snaphosts
      uses: elastic/apm-pipeline-library/.github/actions/snapshoty-simple@current
      with:
        config: '.ci/snapshoty.yml'
        vaultUrl: ${{ secrets.VAULT_ADDR }}
        vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
        vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
