---
## Workflow to process the JUnit test results and add a report to the checks.
name: test-linux-reporter
on:
  workflow_run:
    workflows:
      - test-linux
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    name: Linux Test Summary
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/test-report@current
        with:
          artifact: test-results-linux
          name: Linux Tests Summary
          path: "junit-*.xml"
          reporter: java-junit
          list-suites: 'failed'
          list-tests: 'failed'
